project_id = "ahfytcfndbnwrabryjnz"
[functions.geocoding]
enabled = true
verify_jwt = true
import_map = "./functions/geocoding/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/geocoding/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/geocoding/*.html" ]
